name: CI com Shell Script

on:
  push:
    branches:
      - main

jobs:
  executar-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Conceder permissão de execução aos scripts
        run: chmod +x 01-terminal-bash/scripts/*.sh

      - name: Executar script de informações do sistema
        run: ./01-terminal-bash/scripts/system-info.sh
